### ISSUE TITLE
Problem after authentication

### ISSUE THREAD

**Issue by jc13git** [csm10495/pyhtcc#1]
Running into a problem after authentication and while trying to parse the location from the resulting URL.  Possible that they have changed the portal to default to a different URL on login?

normaluser@NS4:~ $ pyhtcc -u username -p password -d -s
2020-11-07 14:46:09,039 - pyhtcc.pyhtcc.py:215 - DEBUG - Starting authentication attempt #1
2020-11-07 14:46:10,261 - pyhtcc.pyhtcc.py:236 - DEBUG - Attempting authentication for username
2020-11-07 14:46:11,032 - pyhtcc.pyhtcc.py:248 - DEBUG - resulting url from authentication: https://www.mytotalconnectcomfort.com/portal/Device/Control/12345678
Traceback (most recent call last):
  File "/home/pi/.local/bin/pyhtcc", line 10, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python3.7/site-packages/pyhtcc/__main__.py", line 43, in main
    pyhtcc = PyHTCC(user, password)
  File "/home/pi/.local/lib/python3.7/site-packages/pyhtcc/pyhtcc.py", line 204, in __init__
    self.authenticate()
  File "/home/pi/.local/lib/python3.7/site-packages/pyhtcc/pyhtcc.py", line 217, in authenticate
    return self._do_authenticate()
  File "/home/pi/.local/lib/python3.7/site-packages/pyhtcc/pyhtcc.py", line 258, in _do_authenticate
    self._locationId = int(self._locationId)
ValueError: invalid literal for int() with base 10: 'Device'

**Comment by csm10495** [comment]
Maybe the site was down or something? Still works fine for me.

**Comment by jc13git** [comment]
I can use the browser and phone app, and it looks like authentication is successful with the python library.  Since I have only a single t-stat in a single location, when I login through the browser it takes me directly to the t-stat control page.  The python library looks like it's trying to parse out the location_id from that resulting URL that isn't present.  Do you have more than 1 t-stat in your portal?

**Comment by jc13git** [comment]
Just an update - I created a dummy location in the portal so it takes me to a location selection by default when I login.  Still doesn't work though.  The URL returned now after login is "https://www.mytotalconnectcomfort.com/portal/Locations", but still doesn't parse correctly at line 256.  If I hardcode my location, it does work and I can see the status as I should.

**Comment by jc13git** [comment]
And one last comment - I bet that having two t-stats in a location will default the login page to "https://www.mytotalconnectcomfort.com/portal/12345678/Zones" so that the URL parsing will work.  I have a second one that I have yet to install, so I'll report back once complete.  Thanks for the nice looking library too!

**Comment by csm10495** [comment]
I have 2 thermostats. That must be the difference in behavior. When you hardcode the location in code instead of using the faulty splitting logic, it works.

We can likely make the logic work in both cases to find the location in the redirect url.

How did you make it redirect to a url without a location id? When it does that, any chance the location id is in the resulting response data?

**Comment by jc13git** [comment]
I'm basically ignoring what's returned from the login and doing this:

        #self._locationId = int(self._locationId)
        self._locationId = 12345678

After that it seems to work as it should.  I guess the problem with having only one location and one t-stat is that it defaults to the returned URL being the direct control URL containing the device ID instead of the location.  I can work around it until I get the second one installed - thanks for your help.

**Comment by csm10495** [comment]
But is 12345678 just a made up number (or a replacement for the actual id)?

I'm trying to figure out if the field is ignored in the case of a single thermostat.

**Comment by jc13git** [comment]
Yes - sorry , that number is my sanitized representation of my real locationID.  I'm providing it with my actual locationID in the code.

**Comment by csm10495** [comment]
How did you get it then?

**Comment by jc13git** [comment]
When I login using the browser, it takes me directly to the visual representation of the t-stat.  I can then click a ling that takes me back a level which shows my thermostats in that location, and then viewing the url shows the locationID.

Control Center-> My Locations->**Thermostat(s) in Home**->Rheem Control

**Comment by csm10495** [comment]
@jc13git can you try the change i made in 06ea78cf166c1e1bc8022504ef2cb8ec92de0afc ? I think it might now work for your 1 thermostat case.

**Comment by jc13git** [comment]
Looks like that works for me - thanks for that!
