### ISSUE TITLE
non-json data returned within get_zones_info, masking authorization error

### ISSUE THREAD

**Issue by cjkrolak** [csm10495/pyhtcc#10]
authorization error manifests as a JSONDecodeError due to the function get_zones_info expecting json response and receiving an HTML response.  I am not sure yet what triggered the authorization error, I had been polling this thermostat for days on a 10 minute interval before this happens.  I see this type of failure once a month or so.  For this issue ticket I am requesting a code update to detect the authorization error and not mask it with a JSONDecodeError.

```
2023-04-16 18:38:01,396 - pyhtcc.pyhtcc.py:221 - ERROR - Unable to decode json data returned by GetZoneList. Data was:
 <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>401 - Unauthorized: Access is denied due to invalid credentials.</title>
<style type="text/css">
<!--
body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
fieldset{padding:0 15px 10px 15px;} 
h1{font-size:2.4em;margin:0;color:#FFF;}
h2{font-size:1.7em;margin:0;color:#CC0000;} 
h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} 
#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
background-color:#555555;}
#content{margin:0 0 0 2%;position:relative;}
.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
-->
</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>401 - Unauthorized: Access is denied due to invalid credentials.</h2>
  <h3>You do not have permission to view this directory or page using the credentials that you supplied.</h3>
 </fieldset></div>
</div>
</body>
</html>
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.9/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/pi/.local/lib/python3.9/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/home/pi/.local/lib/python3.9/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/home/pi/.local/lib/python3.9/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by cjkrolak** [comment]
sending an Accept header may help if the Honeywell server is configured to return error messages in json format, 

e.g. headers={'accept': 'application/json'}

ref:
https://stackoverflow.com/questions/52488117/python-requests-randomly-breaks-with-jsondecodeerror
https://stackoverflow.com/questions/30841398/http-get-request-get-html-page-code-instead-of-expected-json-response

**Comment by csm10495** [comment]
Unfortunately, the Honeywell server ignores the accept header. 

That's such an odd error to get after logging in. Did the password change? I've wanted to go back and make the requests logic a bit smarter for a while now. iirc it doesn't even check status codes all the time at the moment.

Similarly I've seen: 

```
2023-02-11 20:50:07,502 - pyhtcc.pyhtcc.py:508 - ERROR - Unable to decode json data returned by SubmitControlScreenChanges. Data was:
...
Sorry, an error occurred while processing your request.
...
```

which was odd. I think mine happens when they're doing some form of internal maintenance... yours sounds so much like a password change. 

Either way, yeah i can try to make it raise something a bit more majestic when it sees known cases.

**Comment by csm10495** [comment]
I've updated the code and (in a sec will) release(d) a new version. It will have the ability to raise:
`UnauthorizedError` in your case and a `UnexpectedError` in my case.

Looking at all the code here, I'm tempted to refactor, move more around, and clean up some things.. (I've learned a bit since i wrote the original version of this code).

Thanks for reporting. Feel free to reopen if it catch your case!

**Comment by cjkrolak** [comment]
> Unfortunately, the Honeywell server ignores the accept header.
> 
> That's such an odd error to get after logging in. Did the password change? I've wanted to go back and make the requests logic a bit smarter for a while now. iirc it doesn't even check status codes all the time at the moment.
> 
> Similarly I've seen:
> 
> ```
> 2023-02-11 20:50:07,502 - pyhtcc.pyhtcc.py:508 - ERROR - Unable to decode json data returned by SubmitControlScreenChanges. Data was:
> ...
> Sorry, an error occurred while processing your request.
> ...
> ```
> 
> which was odd. I think mine happens when they're doing some form of internal maintenance... yours sounds so much like a password change.
> 
> Either way, yeah i can try to make it raise something a bit more majestic when it sees known cases.

Thanks for the fast response Charles.  No the password is never changing. 

I poll the get_zones_info() at 10 minute intervals perpetually to monitor my thermostat.

I forgot to mention in my original problem statement that I have added retries to my code and that mitigates many of these decode errors (retry loop will wait 60 seconds and then resend the get_zones_info() command, looping up to 10 times before giving up).  intermittent failures (works on first retry) are occurring about 6 times per day.  Fatal failures (fail 10 times in succession) are happening about once every 3 months or so.  Maybe these quarterly fatal failures are some type of site maintenance as you suspect.  I figured it was some flakiness on the server side sending a corrupted response since it was largely intermittent, just yesterday I dug a little deeper and looked into the pyhtcc log file and found the HTML response.  It looks like GetZoneList is always failing on page 1 post as far as I can tell in the logs.
