### ISSUE TITLE
Regex: IndexError: list index out of range

### ISSUE THREAD

**Issue by stefets** [csm10495/pyhtcc#18]
Trying the lib to patch an issue with my main electrical panel board; I want to control the thermostat with a daemon but I have an error with the most minimal script I can do.

```
from pyhtcc import PyHTCC
p = PyHTCC("username", "password")
print (p.get_zones_info())
```
Give the error:
```
Traceback (most recent call last):
  File "/home/stefets/src/tcc/app.py", line 3, in <module>
    print (p.get_zones_info())
  File "/home/stefets/.venv/tcc/lib/python3.10/site-packages/pyhtcc/pyhtcc.py", line 759, in get_zones_info
    name = self._get_name_for_device_id(device_id)
  File "/home/stefets/.venv/tcc/lib/python3.10/site-packages/pyhtcc/pyhtcc.py", line 515, in decorator
    return func(self, *args, **kwargs)
  File "/home/stefets/.venv/tcc/lib/python3.10/site-packages/pyhtcc/pyhtcc.py", line 621, in _get_name_for_device_id
    name = re.findall(r'id=\s?"ZoneName"\s?>(.*) Control<', result.text)[0]
IndexError: list index out of range
```

**Comment by csm10495** [comment]
By any chance do you have multiple locations in your TCC account?

Ref #17

**Comment by stefets** [comment]
> do you have multiple locations in your TCC account?

Hello! No, I have one zone, one location named **Home** with one central thermostat.

The regex failed with index [0]

I forked the lib and I will inspect what goes out off the result variable at line 616;

**Comment by csm10495** [comment]
Cool. Let me know what you find. Happy to take a PR for something slightly off. Thanks!

**Comment by stefets** [comment]
Yes I will PR a fix if it goes on the right way for me. On the other hand, I am looking for an alternative to this thermostat device. The portal is slow as hell, there is no API, lots of hand job and boiler plate work for a custom solution, Honeywell are stuck in the 80's. They sucks.

**Comment by stefets** [comment]
# OMFG - Honeywell S*CKS!

### This is a localization issue because my profile is in french

Chrome inspection in french - **NO MATCH**:
`<h1 id="ZoneName">Commande ThermostatHome</h1>`

Regex:
`name = re.findall(r'id=\s?"ZoneName"\s?>(.*) Control<', result.text)[0]`

Switching my language in the UI also change the language of my profile and also change the HTML rendered by the portal.

Chrome inspection in english - **MATCH**:
`<h1 id="ZoneName">ThermostatHome Control</h1>`

Regex:
`name = re.findall(r'id=\s?"ZoneName"\s?>(.*) Control<', result.text)[0]`


I will not PR a fix at this moment, instead I'll switch my profile in english to go further.

**Comment by stefets** [comment]
## WORKAROUND

### Set your portal profile in english
