### ISSUE TITLE
"International" URL

### ISSUE THREAD

**Issue by alexespencer** [csm10495/pyhtcc#4]
Some uses mights need URLs that look like this: https://international.mytotalconnectcomfort.com/Account/Login?task=logout

Note "international" in the URL. We might want to have the code accept a customer path, or a switch for these users?

**Comment by alexespencer** [comment]
So..worse news - there is no API. It looks like HTML passing would be the way to go?

**Comment by csm10495** [comment]
This library doesn't really support TCC instances that don't use /portal. I
think it may only apply to the US version.

I'm definitely open to the possibility of a PR to add support, but it
currently definitely won't work.

- Charlie Scott Machalow

**Comment by alexespencer** [comment]
I think it'll be a lot of work - looking at the calls the site makes, all the returns from things like /Locations /Zones etc are full HTML pages, not JSON packets... I've dropped support at Honeywell an email...here's hoping. If there is an API, I'd be happy to submit a PR
