### ISSUE TITLE
Incorrect spelling in method names.  

### ISSUE THREAD

**Issue by psfales** [csm10495/pyhtcc#9]
The correct spelling of the word is "permanent"

so the method names 

- set_permananent_heat_setpoint()
- set_permananent_cool_setpoint()

should really be

- set_permanent_heat_setpoint()
- set_permanent_cool_setpoint()

**Comment by csm10495** [comment]
It's pretty amazing that no one has ever noticed or pointed this out before.

The fix is to mark the old name as deprecated and redirect to the new name for some time before removal.

**Comment by csm10495** [comment]
Fixed with version 0.1.11 and 0.1.12.. now on pypi: https://pypi.org/project/pyhtcc/0.1.12/ .. thanks!

The old names still work, but are deprecated... one day i'll get rid of them.. but probably not for a while.

**Comment by psfales** [comment]
Thanks!   (Thanks for the fix, and for the amazingly quick turnaround!)
